# Generated by Django 5.1.3 on 2024-12-09 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bike', '0002_remove_bicycle_description_bicycle_time_taken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bicycle',
            name='time_taken',
            field=models.IntegerField(default=0),
        ),
    ]
