# Generated by Django 4.2 on 2024-12-09 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bike', '0007_checkin_owner_imagemodel_price_imagemodel_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkin',
            name='owner',
        ),
    ]
